### ISSUE TITLE
기기 관련 로직

### ISSUE THREAD

**Issue by jcw1031** [LikeKNU/LikeKNU#61]
- [ ] ~~기기 등록 여부 조회~~

### @ahma0 
- [x] 신규 기기 등록( #66 )
- [x] 기기 캠퍼스 수정 ( #68 )
- [ ] 기기 FCM 토큰 등록 ( #71 )

### @jcw1031 
- [x] 기기 알림 구독 조회
- [x] 기기 알림 구독 수정
- [ ] 기기 알림 켜기/끄기
